language: java
sudo: required
services:
  - docker
jobs:
  include:
    - jdk: openjdk8
      env:
        - BUILD_PUBLISH=true
        - SONAR_ANALYSIS=false
    - jdk: openjdk11
      env:
        - BUILD_PUBLISH=false
        - SONAR_ANALYSIS=true
    - jdk: openjdk13
      env:
        - BUILD_PUBLISH=false
        - SONAR_ANALYSIS=false
script: ./travisBuild.sh
after_success:
  - ./sonarcloud.sh
  - bash <(curl -s https://codecov.io/bash)
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

